import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customersRouter from "./customers";
import vendorsRouter from "./vendors";
import accountsRouter from "./accounts";
import invoicesRouter from "./invoices";
import billsRouter from "./bills";
import paymentsRouter from "./payments";
import bankingRouter from "./banking";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import taxRatesRouter from "./tax-rates";
import journalEntriesRouter from "./journal-entries";
import transfersRouter from "./transfers";
import expensesRouter from "./expenses";
import salesReceiptsRouter from "./sales-receipts";
import creditNotesRouter from "./credit-notes";
import vendorCreditsRouter from "./vendor-credits";
import estimatesRouter from "./estimates";
import purchaseOrdersRouter from "./purchase-orders";
import statementsRouter from "./statements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(customersRouter);
router.use(vendorsRouter);
router.use(accountsRouter);
router.use(invoicesRouter);
router.use(billsRouter);
router.use(paymentsRouter);
router.use(bankingRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(taxRatesRouter);
router.use(journalEntriesRouter);
router.use(transfersRouter);
router.use(expensesRouter);
router.use(salesReceiptsRouter);
router.use(creditNotesRouter);
router.use(vendorCreditsRouter);
router.use(estimatesRouter);
router.use(purchaseOrdersRouter);
router.use(statementsRouter);

export default router;
